POST http://localhost:9000/admin/policy-groups/policy_group_01HCYTCPQ84XC4DZNVBSE317SS
Content-Type: application/json

{
  "policies": [
    {
      "id": "policy_01HCYJ0DZH39ZSAB1JQ1SQK4XZ"
    }
  ]
}

