GET http://localhost:9000/admin/policies/policy_01HCZWCDQSKG1GQ25BR3BVEN7S
Content-Type: application/json

{
  "name": "a",
  "method": "POST",
  "base_router": "defined",
  "custom_regex": "asdsa"

}

